name: wordle
description: 'Wordle.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  intl: any

  flutter:
    sdk: flutter
  http: ^1.2.0
  google_fonts: ^6.2.0
  flutter_bloc: ^8.1.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  get_it: ^7.7.0
  shared_preferences: ^2.2.3
  flash: ^3.1.0
  lottie: ^3.1.2
  flutter_slidable: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  build_runner: ^2.4.8

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/lottie/
